### PR TITLE
Add wasm crate

### PR DESCRIPTION
**Pull request by tkmct**
- [x] minimam wasm entry point

Need discussion of how to publish Wasm and npm package. Publishing package with CI on separate PR.

### CODE REVIEW

**Comment by syuhei176** [comment]
@tkmct I think we can make warm bridge in another repository like https://github.com/cryptoeconomicslab/plasma-android-sdk/blob/219a9758fa4d449657b79289cd9f7d66a6c8a838/rust/Cargo.toml.

Which do you think better is?
If we have warm in this repo, we can check whether it can be build or not in CI. But how do we use warm file from another repository?

**Comment by tkmct** [comment]
I was thinking to publish wasm binary file to wapm in this repo and use it from browser-sdk which is just a npm module separate repository because if we build binary in separated repository, it's difficult to setup publish CI for a few reasons like versioning.
But you are right, it's little bit messy to build and publish within this repo.

So, my idea is like this.
For now, just put this crate in this repo and make sure it works fine. And when we are ready to focus on client side stuff and Publishing process, it's time to separate browser-sdk in another repository.

(And another concern is, is it really good way to publish binray to wapm.)

**Comment by syuhei176** [comment]
> I was thinking to publish wasm binary file to wapm in this repo and use it from browser-sdk which is just a npm module separate repository because if we build binary in separated repository, it's difficult to setup publish CI for a few reasons like versioning.
> But you are right, it's little bit messy to build and publish within this repo.
> 
> So, my idea is like this.
> For now, just put this crate in this repo and make sure it works fine. And when we are ready to focus on client side stuff and Publishing process, it's time to separate browser-sdk in another repository.
> 
> (And another concern is, is it really good way to publish binray to wapm.)

Nice! I got it!

**Comment by tkmct** [comment]
Thanks!! I just create another issue to separate wasm crate. (Actually not as wasm crate but as npm module)

**Pull request merged**
